import Head from 'next/head'
import Image from 'next/image'
import { useEffect } from 'react'
import styles from '../../styles/Home.module.css'
import { LineChart, XAxis, YAxis, Tooltip, CartesianGrid, Line } from 'recharts'


export default function UserProfile({ requests, device }) {

  const requestData = requests.sort((a, b) => new Date(a.created) - new Date(b.created))
  for (let i = 0; i < requestData.length; i++) {  
    requestData[i] = {
        ...requestData[i],
        ...requestData[i].decoded_payload,
        created: new Date(requestData[i].created).toLocaleString()
    }
    if(requestData[i].TempC_DS > 100) {
        console.log(i)
        console.log(requestData[i])
    }
  }
  const lastRequest = requestData[requestData.length - 1]

  console.log(device)
    
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          {device.name}
        </h1>
        <table>
            <body>
                <tr style={{color: "#9510AA"}}>
                    <td>Inside: </td>
                    <td>{lastRequest.TempC_SHT}</td>
                </tr>
                <tr style={{color: "#387908"}}>
                    <td>Outside: </td>
                    <td>{lastRequest.TempC_DS}</td>
                </tr>
                <tr style={{color: "#ff7300"}}>
                    <td>Humidity inside</td>
                    <td>{lastRequest.Hum_SHT}</td>
                </tr>
            </body>
        </table>
        
        <LineChart
          width={400}
          height={200}
          data={requestData}
          margin={{ top: 5, right: 20, left: 10, bottom: 5 }}
        >
          {/* <XAxis dataKey="created" /> */}
          <Tooltip />
          {/* <CartesianGrid stroke="#f5f5f5" /> */}
          {/* <Line type="monotone" dataKey="Hum_SHT" stroke="#ff7300" yAxisId={0} /> */}
          <Line type="monotone" dataKey="TempC_DS" stroke="#387908" yAxisId={0} />
          <Line type="monotone" dataKey="TempC_SHT" stroke="#9510AA" yAxisId={1} />
        </LineChart>

        <LineChart
          width={400}
          height={100}
          data={requestData}
          margin={{ top: 5, right: 20, left: 10, bottom: 5 }}
        >
          <XAxis dataKey="created" />
          <Tooltip />
          {/* <CartesianGrid stroke="#f5f5f5" /> */}
          <Line type="monotone" dataKey="Hum_SHT" stroke="#ff7300" yAxisId={0} />
        </LineChart>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export const getServerSideProps = async (context) => {
    const { params } = context
    const { deviceId } = params
    console.log(deviceId)
    const res = await fetch('http://localhost:4000/v1/request/device/' + deviceId, {
        method: 'GET',
        headers: {
            'Content-Type': 'application/json'
        }
    })
    const data = await res.json()

    const resDevice = await fetch('http://localhost:4000/v1/device/' + deviceId + "?order=asc", {
        method: 'GET',
        headers: {
            'Content-Type': 'application/json'
        }
    })
    const device = await resDevice.json()

    const requests = data.requests
    return {
        props: {
          requests,
          device: device.data
        }
    }
}
