import Head from 'next/head'
import Image from 'next/image'
import { useEffect } from 'react'
import styles from '../../styles/Home.module.css'
import { LineChart, XAxis, Tooltip, CartesianGrid, Line } from 'recharts'


export default function UserProfile({ requests }) {

  const a = requests.map((request) => 
    request.decoded_payload
  )
  console.log(a)
  console.log(requests)

  // console.log(requests)
    
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        
        <LineChart
          width={400}
          height={400}
          data={[{uv: 400, pv: 2400, amt: 2400}, {uv: 300, pv: 1398, amt: 2210}, {uv: 200, pv: 9800, amt: 2290}, {uv: 278, pv: 3908, amt: 2000}, {uv: 189, pv: 4800, amt: 2181}, {uv: 239, pv: 3800, amt: 2500}, {uv: 349, pv: 4300, amt: 2100}]}
          margin={{ top: 5, right: 20, left: 10, bottom: 5 }}
        >
          <XAxis dataKey="name" />
          <Tooltip />
          {/* <CartesianGrid stroke="#f5f5f5" /> */}
          <Line type="monotone" dataKey="uv" stroke="#ff7300" yAxisId={0} />
          <Line type="monotone" dataKey="pv" stroke="#387908" yAxisId={1} />
        </LineChart>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export const getServerSideProps = async (context) => {
    const { params } = context
    const { username } = params
    console.log(username)
    const res = await fetch(process.env.NEXT_PUBLIC_SERVER + '/request/user/' + username, {
        method: 'GET',
        headers: {
            'Content-Type': 'application/json'
        }
    })

    const data = await res.json()
    const requests = data.requests
    return {
        props: {
          requests
        }
    }
}
